# picom vgit-df4c6
# config made by m33tkr33t

backend = "xrender";
vsync = false;   
dither = false;   
glx-use-cg = true;
paint-on-overlay = false;
use-damage = true;
xrender-sync-fence = true;
glx-no-rebind-pixmap = true;
glx-no-stencil = true;

unredir-if-possible = true;

corner-radius = 0;
round-borders = 1;
rounded-corners-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'"
];

active-opacity = 1.0;
inactive-opacity = 1.0;
frame-opacity = 1.0;
inactive-opacity-override = false;
focus-exclude = [
  "class_g = 'Firefox'",
];

opacity-rule = [
   "100:class_g = 'slop'", 
   "100:class_g = 'Thunar'",
   "100:class_g = 'Firefox'",
];

fading = true;
fade-in-step = 0.06
fade-out-step = 0.06
fade-delta = 6

animations = true;
animation-stiffness = 150.0;
animation-stiffness-in-tag = 150.0;
animation-stiffness-tag-change = 150.0;
animation-stiffness-tag-change = 150.0;
animation-dampening = true;#
animation-clamping = true;
animation-mass = 0.5;
animation-for-open-window = "zoom";
animation-for-unmap-window = "squeeze";
animation-for-transient-window = "slide-down"; 
animation-speed = 55;
animation-exclude = [
  "class_g = 'slop'"
];

