# picom vgit-df4c6
# config made by m33tkr33t

backend = "xrender";
vsync = false;          
use-damage = false;
xrender-sync-fence = true;
glx-no-rebind-pixmap = true;
glx-no-stencil = true;

unredir-if-possible = true;
unredir-if-possible-exclude = [ 
  "class_g = 'Minecraft'" 
];

corner-radius = 8;
rounded-corners-exclude = [
  "class_g = 'i3-frame'",
  "window_type = 'dock'",
  "window_type = 'desktop'"
];

active-opacity = 1.0;
inactive-opacity = 0.80;
frame-opacity = 1.0;
inactive-opacity-override = false;
focus-exclude = [
  "class_g = 'Firefox'",
];
opacity-rule = [
   "100:class_g = 'slop'", 
   "85:class_g = 'Thunar'",
   "100:class_g = 'Firefox'",
];

fading = true;
fade-in-step = 0.04;
fade-out-step = 0.04;
fade-delta = 3;

animations = true;
animation-stiffness = 250.0;
animation-stiffness-in-tag = 150.0;
animation-stiffness-tag-change = 40.0;
animation-dampening = true;
animation-clamping = true;
animation-mass = 0.8;
animation-for-open-window = "zoom";
animation-for-unmap-window = "squeeze";
animation-for-transient-window = "slide-down"; 
animation-speed = 55;
animation-exclude = [
  "class_g = 'slop'"
];

