family Monospace
font_size        11.0

background_opacity 0.50
window_padding_width 0
confirm_os_window_close 0
animation_loading_page_delay 0
visual_bell_duration 1
scrollback_lines 2000
enable_audio_bell no

shell fish

open_url_with default
url_prefixes http https file ftp
detect_urls yes
url_color #73daca

cursor_shape beam
cursor_shape_unfocused block
cursor_blink_interval 0.5
cursor_trail 1
cursor_trail_decay 0.1 0.4

wheel_scroll_multiplier 5
touch_scroll_multiplier 5

input_delay 0
update_check_interval 0

tab_bar_edge top
tab_bar_style powerline
tab_powerline_style round
